# Generated by Django 3.0.5 on 2020-04-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='pub_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Идентефикатор публикации'),
        ),
    ]
